--
-- PostgreSQL database dump
--

\restrict ZkmAgOm8BncdOpx2zK1ICqT5571MZe0mklXPaUtPVbH3obawmyLCdOW83cphG4L

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-05 22:06:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 19932)
-- Name: books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255) NOT NULL,
    genre character varying(255) NOT NULL,
    isbn character varying(255) NOT NULL,
    stock integer NOT NULL,
    title character varying(255) NOT NULL
);


ALTER TABLE public.books OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 19931)
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 19946)
-- Name: loans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.loans (
    id bigint NOT NULL,
    due_date date NOT NULL,
    loan_date date NOT NULL,
    return_date date,
    status character varying(255) NOT NULL,
    book_id bigint NOT NULL,
    member_id bigint NOT NULL,
    CONSTRAINT loans_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'RETURNED'::character varying, 'OVERDUE'::character varying])::text[])))
);


ALTER TABLE public.loans OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 19945)
-- Name: loans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.loans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 19959)
-- Name: members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.members (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL
);


ALTER TABLE public.members OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 19958)
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5027 (class 0 OID 19932)
-- Dependencies: 220
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.books VALUES (1, 'Andhika', 'testing', 'testing', 1, 'Buku Belajar Java');
INSERT INTO public.books VALUES (2, 'Robert C. Martin', 'Technology', '978-0132350884', 5, 'Clean Code');
INSERT INTO public.books VALUES (3, 'Andrew Hunt', 'Technology', '978-0201616224', 3, 'The Pragmatic Programmer');
INSERT INTO public.books VALUES (4, 'Gang of Four', 'Technology', '978-0201633610', 4, 'Design Patterns');
INSERT INTO public.books VALUES (5, 'James Clear', 'Self-Help', '978-0735211292', 6, 'Atomic Habits');
INSERT INTO public.books VALUES (6, 'Cal Newport', 'Self-Help', '978-1455586691', 4, 'Deep Work');
INSERT INTO public.books VALUES (7, 'J.K. Rowling', 'Fiction', '978-0439708180', 7, 'Harry Potter and the Sorcerer''s Stone');
INSERT INTO public.books VALUES (8, 'J.R.R. Tolkien', 'Fiction', '978-0547928227', 5, 'The Hobbit');
INSERT INTO public.books VALUES (9, 'Yuval Noah Harari', 'History', '978-0062316097', 4, 'Sapiens');
INSERT INTO public.books VALUES (10, 'Daniel Kahneman', 'Psychology', '978-0374533557', 3, 'Thinking, Fast and Slow');
INSERT INTO public.books VALUES (11, 'Craig Walls', 'Technology', '978-1617292545', 2, 'Spring Boot in Action');


--
-- TOC entry 5029 (class 0 OID 19946)
-- Dependencies: 222
-- Data for Name: loans; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.loans VALUES (1, '2026-05-06', '2026-05-05', '2026-05-05', 'RETURNED', 1, 1);
INSERT INTO public.loans VALUES (2, '2026-05-09', '2026-04-25', NULL, 'ACTIVE', 1, 1);
INSERT INTO public.loans VALUES (3, '2026-04-29', '2026-04-15', NULL, 'OVERDUE', 2, 2);
INSERT INTO public.loans VALUES (4, '2026-05-14', '2026-04-30', NULL, 'ACTIVE', 3, 3);
INSERT INTO public.loans VALUES (5, '2026-04-19', '2026-04-05', '2026-04-18', 'RETURNED', 4, 1);
INSERT INTO public.loans VALUES (6, '2026-05-16', '2026-05-02', NULL, 'ACTIVE', 5, 4);
INSERT INTO public.loans VALUES (7, '2026-05-04', '2026-04-20', NULL, 'OVERDUE', 6, 5);
INSERT INTO public.loans VALUES (8, '2026-04-24', '2026-04-10', '2026-04-23', 'RETURNED', 7, 2);


--
-- TOC entry 5031 (class 0 OID 19959)
-- Dependencies: 224
-- Data for Name: members; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.members VALUES (1, 'dimas@gmail.com', 'fajar', '0873847875543');
INSERT INTO public.members VALUES (2, 'budi.santoso@email.com', 'Budi Santoso', '081234567890');
INSERT INTO public.members VALUES (3, 'siti.rahayu@email.com', 'Siti Rahayu', '082345678901');
INSERT INTO public.members VALUES (4, 'ahmad.fauzi@email.com', 'Ahmad Fauzi', '083456789012');
INSERT INTO public.members VALUES (5, 'dewi.lestari@email.com', 'Dewi Lestari', '084567890123');
INSERT INTO public.members VALUES (6, 'rizky.pratama@email.com', 'Rizky Pratama', '085678901234');


--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 219
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.books_id_seq', 11, true);


--
-- TOC entry 5039 (class 0 OID 0)
-- Dependencies: 221
-- Name: loans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.loans_id_seq', 8, true);


--
-- TOC entry 5040 (class 0 OID 0)
-- Dependencies: 223
-- Name: members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.members_id_seq', 6, true);


--
-- TOC entry 4868 (class 2606 OID 19944)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 19957)
-- Name: loans loans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT loans_pkey PRIMARY KEY (id);


--
-- TOC entry 4874 (class 2606 OID 19969)
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 19973)
-- Name: members uk9d30a9u1qpg8eou0otgkwrp5d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT uk9d30a9u1qpg8eou0otgkwrp5d UNIQUE (email);


--
-- TOC entry 4870 (class 2606 OID 19971)
-- Name: books ukkibbepcitr0a3cpk3rfr7nihn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT ukkibbepcitr0a3cpk3rfr7nihn UNIQUE (isbn);


--
-- TOC entry 4877 (class 2606 OID 19979)
-- Name: loans fkcx90n1minpb22v3jw4ojinqm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT fkcx90n1minpb22v3jw4ojinqm FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- TOC entry 4878 (class 2606 OID 19974)
-- Name: loans fkokwvlrv6o4i4h3le3bwhe6kie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT fkokwvlrv6o4i4h3le3bwhe6kie FOREIGN KEY (book_id) REFERENCES public.books(id);


-- Completed on 2026-05-05 22:06:45

--
-- PostgreSQL database dump complete
--

\unrestrict ZkmAgOm8BncdOpx2zK1ICqT5571MZe0mklXPaUtPVbH3obawmyLCdOW83cphG4L

